apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-closememo-gateway
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: dev-closememo-gateway
  template:
    metadata:
      labels:
        app: dev-closememo-gateway
    spec:
      containers:
      - image: reg.bitgadak.com/closememo/gateway:202111201603
        name: dev-closememo-gateway
        ports:
        - containerPort: 10080
        env:
        - name: PROFILE
          value: dev
      imagePullSecrets:
      - name: regcred
