apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-closememo-command
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: dev-closememo-command
  template:
    metadata:
      labels:
        app: dev-closememo-command
    spec:
      volumes:
      - name: logs
        emptyDir: {}
      containers:
      - image: reg.bitgadak.com/closememo/command:202209251547
        name: dev-closememo-command
        ports:
        - containerPort: 10081
        env:
        - name: PROFILE
          value: dev
        readinessProbe:
          httpGet:
            path: /health-check
            port: 10081
          initialDelaySeconds: 10
          periodSeconds: 3
        volumeMounts:
        - name: logs
          mountPath: /home/deployer/logs
      - image: openreg.closememo.com/closememo/dev-filebeat:0.1
        name: dev-closememo-command-filebeat
        volumeMounts:
        - name: logs
          mountPath: /target/logs
      hostAliases:
      - ip: 10.10.101.102
        hostnames:
        - dev.kafka1.closememo.com
      - ip: 10.10.101.109
        hostnames:
        - dev.es.closememo.com
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        phase: dev
