apiVersion: apps/v1
kind: Deployment
metadata:
  name: closememo-command-batch
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: closememo-command-batch
  template:
    metadata:
      labels:
        app: closememo-command-batch
    spec:
      containers:
      - image: reg.bitgadak.com/closememo/command-batch:202112292045
        name: closememo-command-batch
        ports:
        - containerPort: 10081
        env:
        - name: PROFILE
          value: real
      hostAliases:
      - ip: 10.10.101.123
        hostnames:
        - db.closememo.com
      - ip: 10.10.101.123
        hostnames:
        - kafka1.closememo.com
      - ip: 10.10.101.110
        hostnames:
        - es.closememo.com
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        phase: real
