apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-closememo-query
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: dev-closememo-query
  template:
    metadata:
      labels:
        app: dev-closememo-query
    spec:
      containers:
      - image: reg.bitgadak.com/closememo/query:latest
        name: dev-closememo-query
        ports:
        - containerPort: 10082
        env:
        - name: PROFILE
          value: dev
      imagePullSecrets:
      - name: regcred
