apiVersion: apps/v1
kind: Deployment
metadata:
  name: closememo-gateway
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: closememo-gateway
  template:
    metadata:
      labels:
        app: closememo-gateway
    spec:
      containers:
      - image: reg.bitgadak.com/closememo/gateway:202204261618
        name: closememo-gateway
        ports:
        - containerPort: 10080
        env:
        - name: PROFILE
          value: real
        readinessProbe:
          httpGet:
            path: /health-check
            port: 10080
          initialDelaySeconds: 10
          periodSeconds: 3
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        phase: real
