apiVersion: apps/v1
kind: Deployment
metadata:
  name: closememo-gateway
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: closememo-gateway
  template:
    metadata:
      labels:
        app: closememo-gateway
    spec:
      volumes:
      - name: logs
        emptyDir: {}
      containers:
      - image: reg.bitgadak.com/closememo/gateway:202205021954
        name: closememo-gateway
        ports:
        - containerPort: 10080
        env:
        - name: PROFILE
          value: real
        readinessProbe:
          httpGet:
            path: /health-check
            port: 10080
          initialDelaySeconds: 10
          periodSeconds: 3
        volumeMounts:
        - name: logs
          mountPath: /home/deployer/logs
      - image: openreg.closememo.com/closememo/filebeat:202205031649
        name: closememo-gateway-filebeat
        volumeMounts:
        - name: logs
          mountPath: /target/logs
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        phase: real
