apiVersion: apps/v1
kind: Deployment
metadata:
  name: closememo-autotag
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: closememo-autotag
  template:
    metadata:
      labels:
        app: closememo-autotag
    spec:
      containers:
      - image: reg.bitgadak.com/closememo/autotag:202112120134
        name: closememo-autotag
        ports:
        - containerPort: 10084
        env:
        - name: PROFILE
          value: real
      hostAliases:
      - ip: 10.10.101.123
        hostnames:
        - kafka1.closememo.com
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        phase: real
