apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-closememo-autotag
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: dev-closememo-autotag
  template:
    metadata:
      labels:
        app: dev-closememo-autotag
    spec:
      containers:
      - image: reg.bitgadak.com/closememo/autotag:latest
        name: dev-closememo-autotag
        ports:
        - containerPort: 10084
        env:
        - name: PROFILE
          value: dev
      imagePullSecrets:
      - name: regcred
