apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-closememo-autotag
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: dev-closememo-autotag
  template:
    metadata:
      labels:
        app: dev-closememo-autotag
    spec:
      containers:
      - image: reg.bitgadak.com/closememo/autotag:202201212315
        name: dev-closememo-autotag
        ports:
        - containerPort: 10084
        env:
        - name: PROFILE
          value: dev
      hostAliases:
      - ip: 10.10.101.102
        hostnames:
        - dev.kafka1.closememo.com
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        phase: dev
