apiVersion: apps/v1
kind: Deployment
metadata:
  name: closememo-query
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: closememo-query
  template:
    metadata:
      labels:
        app: closememo-query
    spec:
      volumes:
      - name: logs
        emptyDir: {}
      containers:
      - image: reg.bitgadak.com/closememo/query:202205031727
        name: closememo-query
        ports:
        - containerPort: 10082
        env:
        - name: PROFILE
          value: real
        readinessProbe:
          httpGet:
            path: /health-check
            port: 10082
          initialDelaySeconds: 10
          periodSeconds: 3
        volumeMounts:
        - name: logs
          mountPath: /home/deployer/logs
      - image: openreg.closememo.com/closememo/filebeat:202205031829
        name: closememo-query-filebeat
        volumeMounts:
        - name: logs
          mountPath: /target/logs
      hostAliases:
      - ip: 10.10.101.123
        hostnames:
        - db.closememo.com
      - ip: 10.10.101.123
        hostnames:
        - kafka1.closememo.com
      - ip: 10.10.101.110
        hostnames:
        - es.closememo.com
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        phase: real
